### ISSUE TITLE
Alarm at "Set" not working

### ISSUE THREAD

**Issue by JonHaas** [GorillaSapiens/tauclock#3] opened 2022-11-16 19:10 UTC
I'm trying to set an alarm for 1 hour before sunset. We are currently camped in a location with are a lot of flys and there are narrow windows after sunrise and before sunset where taking advantage of the outdoors is possible. I want to set an alarm so I don't forget to take advantage of them.

Issue: 
When I try to add an alarm for solar set it seems to be setting alarm for solar rise. Screenshots attached.
![Screenshot_20221116-120854](https://user-images.githubusercontent.com/83779731/202271167-9687c4cd-df3d-4076-b9e5-ff3601518fd6.png)

![Screenshot_20221116-120559](https://user-images.githubusercontent.com/83779731/202271280-b29fdc2a-412e-4804-ad1b-613b2d141461.png)

**Comment by GorillaSapiens** [comment] 2022-11-16 19:13
yeah, that seems broken.  good catch, i'll look into it.

**Comment by GorillaSapiens** [comment] 2022-11-16 21:06
issue caused by faulty AM/PM distinction, should be fixed in v0.18, currently available on http://gorillasapiens.com/tauclock/

**Comment by GorillaSapiens** [comment] 2022-11-19 02:02
assigning to @JonHaas , hoping he will confirm v0.18 works as expected, so we can close this bug out.

**Comment by JonHaas** [comment] 2022-11-19 02:32
It worked as expected. Thank you!

**Comment by GorillaSapiens** [comment] 2022-11-19 18:08
closing issue per previous comments

**Closed as completed by GorillaSapiens** 2022-11-19 18:08 UTC
